# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Test with Maven
      run: |
        cd ServidorWeb-TesteMock
        mvn clean test site
    - run: mkdir report && cp /home/runner/work/C214/C214/ServidorWeb-TesteMock/target/site/*.html report
    - uses: actions/upload-artifact@v3
      with:
        name: Report
        path: report
  
  notification-test:
    runs-on: ubuntu-latest
    env:
      email_destinatario: ${{vars.EMAILDESTINATARIO}}
      test: "testes"
    
    steps:
    - uses: actions/checkout@v3
    - name: Notification

      run: !/usr/bin/env bash scripts/shell-email-test.sh
  
  build:
    needs: test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        cd ServidorWeb-TesteMock
        mvn -B package --file pom.xml
    # storageing artifact build
    - run: mkdir staging && cp /home/runner/work/C214/C214/ServidorWeb-TesteMock/target/ServidorWeb-TesteMock-1.0-SNAPSHOT.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

  notification-finalizado:

    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Notification
      run: sudo bash  scripts/shell-email-finalizado.sh

    